import { Link, useParams } from "react-router-dom";
import { FiArrowLeft, FiBox, FiCalendar, FiMapPin, FiMail, FiPhone, FiTrash2, FiUser } from "react-icons/fi";
import StatusBadge from "../../components/StatusBadge";
import { adminCustomers } from "../../data/adminCustomers";

const CustomerDetail = () => {
  const { customerId } = useParams();
  const customer = adminCustomers.find((entry) => String(entry.id) === customerId);

  if (!customer) return <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center"><p className="font-extrabold text-navy-950">Customer not found</p><Link to="/admin/customers" className="mt-3 inline-block text-sm font-bold text-blue-600">Back to customers</Link></div>;

  const orders = Array.from({ length: customer.orders }, (_, index) => ({ id: `#${1016 - index}`, date: index === 0 ? "Aug 20, 2026" : "Aug 19, 2026", total: customer.totalSpent, product: index === 0 ? "Rhinowalk 2M Heavy Duty Appliance Bundle" : "Kolga Bros Appliance Accessory" }));

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><Link to="/admin/customers" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-slate-500 hover:text-blue-600"><FiArrowLeft size={14} /> Back to customers</Link><div className="mt-4 flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-xl font-extrabold text-blue-600">{customer.initials}</span><div><h1 className="text-3xl font-extrabold tracking-tight text-navy-950">{customer.name}</h1><div className="mt-1 flex flex-wrap items-center gap-2"><p className="text-xs font-semibold text-slate-400">{customer.email}</p><StatusBadge label={customer.status} tone={customer.status === "Subscribed" ? "green" : "slate"} dot={customer.status === "Subscribed"} /></div></div></div></div><button type="button" className="flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-2.5 text-xs font-bold uppercase tracking-wider text-red-600 hover:bg-red-100"><FiTrash2 size={14} /> Delete customer</button></div>

      <div className="grid gap-6 xl:grid-cols-[minmax(260px,0.8fr)_minmax(0,1.8fr)]">
        <section className="h-fit rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-navy-950"><FiUser className="text-blue-600" size={15} /> Account info</p><div className="mt-6 space-y-4"><div className="flex justify-between border-b border-slate-100 pb-4 text-sm"><span className="font-semibold text-slate-400">Total orders</span><b className="text-navy-950">{customer.orders}</b></div><div className="flex justify-between border-b border-slate-100 pb-4 text-sm"><span className="font-semibold text-slate-400">Total spent</span><b className="text-blue-600">£{customer.totalSpent}</b></div><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Last known location</p><p className="mt-2 flex items-start gap-2 text-sm font-semibold text-navy-950"><FiMapPin className="mt-0.5 text-cyan-600" size={14} /> {customer.location || "Unknown"}</p></div><div className="border-t border-slate-100 pt-4 space-y-2 text-xs text-slate-500"><p className="flex items-center gap-2"><FiMail size={13} /> {customer.email}</p><p className="flex items-center gap-2"><FiPhone size={13} /> +44 7624 984192</p></div></div></section>
        <section className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-navy-950"><FiBox className="text-blue-600" size={15} /> Purchase history ({customer.orders})</p><div className="mt-5 max-h-[560px] space-y-3 overflow-y-auto pr-1">{orders.length ? orders.map((order, index) => <article key={order.id} className={`rounded-xl border p-4 ${index === 0 ? "border-blue-200 bg-blue-50/30" : "border-slate-200 bg-white"}`}><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-3"><p className="text-xs font-extrabold text-navy-950">ORDER {order.id} <span className="ml-2 inline-flex items-center gap-1 font-semibold text-slate-400"><FiCalendar size={12} /> {order.date}</span></p><div className="flex items-center gap-2"><b className="text-sm text-navy-950">£{order.total}</b><StatusBadge label="Paid" tone="green" /></div></div><div className="mt-3 flex items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-slate-50 text-blue-600"><FiBox size={17} /></span><p className="min-w-0 flex-1 truncate text-xs font-semibold text-slate-600">{order.product}</p><span className="text-[10px] font-semibold text-slate-400">1 × £{order.total}</span></div></article>) : <div className="rounded-xl border border-dashed border-slate-200 px-6 py-14 text-center"><p className="text-sm font-bold text-slate-500">No orders yet</p><p className="mt-1 text-xs text-slate-400">Purchase history will appear here.</p></div>}</div></section>
      </div>
    </div>
  );
};

export default CustomerDetail;